apiVersion: extensions/v1
kind: Deployment
metadata:
  name: postgres
  namespace: monitoring
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: postges-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: postgres-test
    spec:
      containers:
      - name: postgres
        image: ubuntu/postgres:latest
        args:
          - "--default-authentication-plugin=pgsql_native_password"
          - --character-set-server=utf8
          - --collation-server=utf8_bin
        imagePullPolicy: "IfNotPresent"
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
        env:
          - name: PGSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: zabbix-app
                key: PGSQL_ROOT_PASSWORD
          - name: PGSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                key: PGSQL_DATABASE
                name: zabbix-app   
          - name: PGSQL_USER
            valueFrom:
                secretKeyRef:
                  name: zabbix-app
                  key:  PGSQL_USER
          - name: PGSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: zabbix-app
                key:  PGSQL_PASSWORD
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        volumeMounts:
          - name: pgsql-persistent-storage
            mountPath: /var/lib/pgsql
      ports:
        - containerPort: 5432  
      volumes:
        - name: pgsql-persistent-storage
          persistentVolumeClaim:
            claimName: pgsql-pv-claim     
        
          